export default {
  default: "primary",
  primary: {
    el: {
      root: "flex items-center uppercase leading-tight bg-c1-200 px-5 py-3 text-cWhite border border-c1-200 rounded text-sm font-medium w-auto focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "primary-sm": {
    el: {
      root: "flex items-center uppercase leading-tight bg-c1-200 px-3 py-2 text-cWhite border border-c1-200 rounded text-sm font-medium w-auto hover:bg-c2-400 hover:border-c2-400 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "primary-lg": {
    el: {
      root: "flex items-center uppercase leading-tight bg-c1-200 px-5 py-3 text-cWhite border border-c1-200 rounded text-base font-medium w-auto hover:bg-c2-400 hover:border-c2-400 focus:outline-none",
      left: "",
      middle: "mx-2",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "27",
      iconPrefixHeight: "27",
      iconSuffixName: "",
      iconSuffixWidth: "27",
      iconSuffixHeight: "27",
    },
  },
  "primary-outline": {
    el: {
      root: "flex items-center uppercase leading-tight px-5 py-3 text-c1-200 border border-c1-200 rounded text-sm font-medium w-auto hover:bg-c2-400 hover:border-c2-400 hover:text-cWhite focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "primary-outline-sm": {
    el: {
      root: "flex items-center uppercase leading-tight px-3 py-2 text-c1-200 border border-c1-200 rounded text-sm font-medium w-auto hover:bg-c2-400 hover:border-c2-400 hover:text-cWhite focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "primary-outline-lg": {
    el: {
      root: "flex items-center uppercase leading-tight px-5 py-3 text-c1-200 border border-c1-200 rounded text-base font-medium w-auto hover:bg-c2-400 hover:border-c2-400 hover:text-cWhite focus:outline-none",
      left: "",
      middle: "mx-2",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "27",
      iconPrefixHeight: "27",
      iconSuffixName: "",
      iconSuffixWidth: "27",
      iconSuffixHeight: "27",
    },
  },
  secondary: {
    el: {
      root: "flex items-center uppercase leading-tight bg-c1-500 px-5 py-3 text-cWhite border border-c1-500 rounded text-sm font-medium w-auto hover:bg-c1-800 hover:border-c1-800 focus:outline-none",
      left: "mr-2",
      middle: "",
      right: "ml-2",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "secondary-sm": {
    el: {
      root: "flex items-center uppercase leading-tight bg-c1-500 px-3 py-2 text-cWhite border border-c1-500 rounded text-sm font-medium w-auto hover:bg-c1-800 hover:border-c1-800 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "secondary-lg": {
    el: {
      root: "flex items-center uppercase leading-tight bg-c1-500 px-5 py-3 text-cWhite border border-c1-500 rounded text-base font-medium w-auto hover:bg-c1-800 hover:border-c1-800 focus:outline-none",
      left: "",
      middle: "mx-2",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "27",
      iconPrefixHeight: "27",
      iconSuffixName: "",
      iconSuffixWidth: "27",
      iconSuffixHeight: "27",
    },
  },
  "secondary-outline": {
    el: {
      root: "flex items-center uppercase leading-tight px-5 py-3 text-c1-500 border border-c1-500 rounded text-sm font-medium w-auto hover:text-cWhite hover:bg-c1-500 hover:border-c1-500 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "secondary-outline-sm": {
    el: {
      root: "flex items-center uppercase leading-tight px-3 py-2 text-c1-500 border border-c1-500 rounded text-sm font-medium w-auto hover:text-cWhite hover:bg-c1-500 hover:border-c1-500 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "secondary-outline-lg": {
    el: {
      root: "flex items-center uppercase leading-tight px-5 py-3 text-c1-500 border border-c1-500 rounded text-base font-medium w-auto hover:text-cWhite hover:bg-c1-500 hover:border-c1-500 focus:outline-none",
      left: "",
      middle: "mx-2",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "27",
      iconPrefixHeight: "27",
      iconSuffixName: "",
      iconSuffixWidth: "27",
      iconSuffixHeight: "27",
    },
  },
  tertiary: {
    el: {
      root: "flex items-center uppercase leading-tight bg-c0-300 px-5 py-3 text-cWhite border border-c0-300 rounded text-sm font-medium w-auto hover:bg-c0-500 hover:border-c0-500 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "tertiary-sm": {
    el: {
      root: "flex items-center uppercase leading-tight bg-c0-500 px-3 py-2 text-cWhite border border-c0-500 rounded text-sm font-medium w-auto hover:bg-c0-300 hover:border-c0-300 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "tertiary-lg": {
    el: {
      root: "flex items-center uppercase leading-tight bg-c0-300 px-5 py-3 text-cWhite border border-c0-300 rounded text-base font-medium w-auto hover:bg-c0-500 hover:border-c0-500 focus:outline-none",
      left: "",
      middle: "mx-2",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "27",
      iconPrefixHeight: "27",
      iconSuffixName: "",
      iconSuffixWidth: "27",
      iconSuffixHeight: "27",
    },
  },
  "tertiary-outline": {
    el: {
      root: "flex items-center uppercase leading-tight px-5 py-3 border border-c0-500 rounded text-c0-500 text-sm font-medium w-auto hover:text-cWhite hover:bg-c0-500 hover:border-c0-500 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "tertiary-outline-sm": {
    el: {
      root: "flex items-center uppercase leading-tight px-3 py-2 border border-c0-500 rounded text-c0-500 text-sm font-medium w-auto hover:text-cWhite hover:bg-c0-500 hover:border-c0-500 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "tertiary-outline-lg": {
    el: {
      root: "flex items-center uppercase leading-tight px-5 py-3 border border-c0-500 rounded text-c0-500 text-base font-medium w-auto hover:text-cWhite hover:bg-c0-500 hover:border-c0-500 focus:outline-none",
      left: "",
      middle: "mx-2",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "27",
      iconPrefixHeight: "27",
      iconSuffixName: "",
      iconSuffixWidth: "27",
      iconSuffixHeight: "27",
    },
  },
  "tertiary-rounded": {
    el: {
      root: "flex items-center uppercase leading-tight bg-c0-100 p-1 rounded-full text-cWhite text-sm w-auto focus:outline-none hover:shadow",
      left: "",
      middle: "",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "tertiary-rounded-inv": {
    el: {
      root: "flex items-center uppercase leading-tight bg-c0-300 p-1 rounded-full text-cWhite text-sm w-auto focus:outline-none hover:shadow",
      left: "",
      middle: "",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  success: {
    el: {
      root: "flex items-center uppercase leading-tight bg-cSuccess-500 px-5 py-3 border border-cSuccess-500 rounded text-cWhite text-sm font-medium w-auto hover:opacity-75 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  warning: {
    el: {
      root: "flex items-center uppercase leading-tight bg-cError-500 px-5 py-3 border border-cError-500 rounded text-cWhite text-sm font-medium w-auto hover:opacity-75 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "warning-sm": {
    el: {
      root: "flex items-center uppercase leading-tight bg-cError-500 px-3 py-2 border border-cError-500 rounded text-cWhite text-sm font-medium w-auto hover:opacity-75 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "warning-lg": {
    el: {
      root: "flex items-center uppercase leading-tight bg-cError-500 px-5 py-3 border border-cError-500 rounded text-cWhite text-base font-medium w-auto hover:opacity-75 focus:outline-none",
      left: "",
      middle: "mx-2",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "27",
      iconPrefixHeight: "27",
      iconSuffixName: "",
      iconSuffixWidth: "27",
      iconSuffixHeight: "27",
    },
  },
  "warning-outline": {
    el: {
      root: "flex items-center uppercase leading-tight bg-cWhite px-5 py-3 border border-cError-500 rounded text-cError-500 text-sm font-medium w-auto hover:text-cWhite hover:bg-cError-500 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "warning-outline-sm": {
    el: {
      root: "flex items-center uppercase leading-tight bg-cWhite px-3 py-2 border border-cError-500 rounded text-cError-500 text-sm font-medium w-auto hover:text-cWhite hover:bg-cError-500 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "warning-outline-lg": {
    el: {
      root: "flex items-center uppercase leading-tight px-5 py-3 border border-cError-500 rounded text-cError-500 text-base font-medium w-auto hover:text-cWhite hover:bg-cError-500 focus:outline-none",
      left: "",
      middle: "mx-2",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "27",
      iconPrefixHeight: "27",
      iconSuffixName: "",
      iconSuffixWidth: "27",
      iconSuffixHeight: "27",
    },
  },
  transparent: {
    el: {
      root: "flex items-center uppercase leading-tight bg-cTransparent px-5 py-3 rounded text-c1-200 text-sm w-auto hover:text-cWhite hover:bg-c2-400 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "transparent-sm": {
    el: {
      root: "flex items-center uppercase leading-tight bg-cTransparent px-5 py-3 rounded text-c1-200 text-sm w-auto hover:text-cWhite hover:bg-c2-400 focus:outline-none",
      left: "",
      middle: "mx-4",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  "transparent-lg": {
    el: {
      root: "flex items-center uppercase leading-tight bg-cTransparent px-5 py-3 rounded text-c1-200 text-base w-auto hover:text-cWhite hover:bg-c2-400 focus:outline-none",
      left: "",
      middle: "mx-2",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "27",
      iconPrefixHeight: "27",
      iconSuffixName: "",
      iconSuffixWidth: "27",
      iconSuffixHeight: "27",
    },
  },
  "transparent-rounded": {
    el: {
      root: "flex items-center uppercase bg-cWhite leading-tight p-2 rounded-full text-c0-300 text-sm w-auto hover:bg-c0-100 focus:outline-none",
      left: "",
      middle: "",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "24",
      iconPrefixHeight: "24",
      iconSuffixName: "",
      iconSuffixWidth: "24",
      iconSuffixHeight: "24",
    },
  },
  wrapper: {
    el: {
      root: "w-full focus:outline-none",
      left: "",
      middle: "",
      right: "",
      iconPrefix: "",
      iconSuffix: "",
    },
    assets: {
      iconPrefixName: "",
      iconPrefixWidth: "16",
      iconPrefixHeight: "16",
      iconSuffixName: "",
      iconSuffixWidth: "16",
      iconSuffixHeight: "16",
    },
  },
}
