<?php

namespace Encoda\AWSCognito\Enums;

final class AuthFlowEnums
{
    const ALLOW_ADMIN_USER_PASSWORD_AUTH = 'ALLOW_ADMIN_USER_PASSWORD_AUTH';
    const ALLOW_CUSTOM_AUTH = 'ALLOW_CUSTOM_AUTH';
    const ALLOW_USER_SRP_AUTH = 'ALLOW_USER_SRP_AUTH';
    const ALLOW_USER_PASSWORD_AUTH = 'ALLOW_USER_PASSWORD_AUTH';
    const ALLOW_REFRESH_TOKEN_AUTH = 'ALLOW_REFRESH_TOKEN_AUTH';

}
