export default {
  default: "center-2xl",
  "center-2xl": {
    el: {
      root: "bg-cWhite shadow rounded-lg border border-c1-500 m-auto h-auto w-full overflow-y-auto max-w-2xl max-h-modal p-10 sm:px-24",
      overlayEnter: "opacity-0",
      overlayEnterActive: "transition duration-200 ease-ease-in",
      overlayLeaveActive: "transition duration-200 ease-ease-out",
      overlayLeaveTo: "opacity-0",
      overlay: "fixed top-0 left-0 w-full h-screen bg-cBlack bg-opacity-50",
      enter: "opacity-0",
      enterActive: "transition duration-200 ease-ease-in",
      leaveActive: "transition duration-200 ease-ease-out",
      leaveTo: "opacity-0",
      modalWrapper: "fixed top-0 left-0 w-full h-screen items-center justify-center bg-transparent overflow-y-auto p-8",
    },
  },
  "center-md": {
    el: {
      root: "bg-cWhite shadow rounded-lg border border-c1-500 m-auto h-auto w-full overflow-y-auto max-w-md max-h-modal p-10 sm:px-24",
      overlayEnter: "opacity-0",
      overlayEnterActive: "transition duration-200 ease-ease-in",
      overlayLeaveActive: "transition duration-200 ease-ease-out",
      overlayLeaveTo: "opacity-0",
      overlay: "fixed top-0 left-0 w-full h-screen bg-cBlack bg-opacity-50",
      enter: "opacity-0",
      enterActive: "transition duration-200 ease-ease-in",
      leaveActive: "transition duration-200 ease-ease-out",
      leaveTo: "opacity-0",
      modalWrapper: "fixed top-0 left-0 w-full h-screen items-center justify-center bg-transparent overflow-y-auto p-8",
    },
  },
  "center-3xl": {
    el: {
      root: "bg-cWhite shadow rounded-lg border border-c1-500 m-auto h-auto w-full overflow-y-auto max-w-3xl max-h-modal p-10 sm:px-24",
      overlayEnter: "opacity-0",
      overlayEnterActive: "transition duration-200 ease-ease-in",
      overlayLeaveActive: "transition duration-200 ease-ease-out",
      overlayLeaveTo: "opacity-0",
      overlay: "fixed top-0 left-0 w-full h-screen bg-cBlack bg-opacity-50",
      enter: "opacity-0",
      enterActive: "transition duration-200 ease-ease-in",
      leaveActive: "transition duration-200 ease-ease-out",
      leaveTo: "opacity-0",
      modalWrapper: "fixed top-0 left-0 w-full h-screen items-center justify-center bg-transparent overflow-y-auto p-8",
    },
  },
  "center-5xl": {
    el: {
      root: "bg-cWhite shadow rounded-lg border border-c1-500 m-auto h-auto w-full overflow-y-auto max-w-5xl max-h-modal p-10 sm:px-24",
      overlayEnter: "opacity-0",
      overlayEnterActive: "transition duration-200 ease-ease-in",
      overlayLeaveActive: "transition duration-200 ease-ease-out",
      overlayLeaveTo: "opacity-0",
      overlay: "fixed top-0 left-0 w-full h-screen bg-cBlack bg-opacity-50",
      enter: "opacity-0",
      enterActive: "transition duration-200 ease-ease-in",
      leaveActive: "transition duration-200 ease-ease-out",
      leaveTo: "opacity-0",
      modalWrapper: "fixed top-0 left-0 w-full h-screen items-center justify-center bg-transparent overflow-y-auto p-8",
    },
  },
  "fixed-left": {
    el: {
      root: "bg-cWhite shadow rounded-lg border border-c1-500 fixed top-0 left-0 h-screen w-full overflow-y-auto max-w-xl",
      overlayEnter: "opacity-0",
      overlayEnterActive: "transition duration-200 ease-ease-in",
      overlayLeaveActive: "transition duration-200 ease-ease-out",
      overlayLeaveTo: "opacity-0",
      overlay: "fixed top-0 left-0 w-full h-screen bg-cBlack bg-opacity-50",
      enter: "opacity-0",
      enterActive: "transition duration-200 ease-ease-in",
      leaveActive: "transition duration-200 ease-ease-out",
      leaveTo: "opacity-0",
      modalWrapper: "fixed top-0 left-0 w-full h-screen items-center justify-center bg-transparent overflow-y-auto p-8",
    },
  },

  "center-full": {
    el: {
      root: "bg-cWhite shadow rounded-lg border border-c1-500 m-auto h-full w-full overflow-y-auto  max-h-modal p-10 ",
      overlayEnter: "opacity-0",
      overlayEnterActive: "transition duration-200 ease-ease-in",
      overlayLeaveActive: "transition duration-200 ease-ease-out",
      overlayLeaveTo: "opacity-0",
      overlay: "fixed top-0 left-0 w-full h-screen bg-cBlack bg-opacity-50",
      enter: "opacity-0",
      enterActive: "transition duration-200 ease-ease-in",
      leaveActive: "transition duration-200 ease-ease-out",
      leaveTo: "opacity-0",
      modalWrapper: "fixed top-0 left-0 w-full h-screen items-center justify-center bg-transparent overflow-y-auto p-8",
    },
  },
}
